<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-G790OGBU" name="com.menumitratCommonAPITestScript.loginTestScript" tests="1" failures="0" timestamp="5 May 2025 08:21:13 GMT" time="1.593" errors="1">
  <testcase name="verifyloginUsingValidInputData" time="1.593" classname="com.menumitratCommonAPITestScript.loginTestScript">
    <error type="com.menumitra.utilityclass.customException" message="Login verification failed: Error validating response: success response validate failed: Acutal response does not matched expected response expected [{msg=Your OTP is sent successfully., st=1, role=owner}] but found [{role=owner, detail=Your OTP is sent successfully.}]">
      <![CDATA[com.menumitra.utilityclass.customException: Login verification failed: Error validating response: success response validate failed: Acutal response does not matched expected response expected [{msg=Your OTP is sent successfully., st=1, role=owner}] but found [{role=owner, detail=Your OTP is sent successfully.}]
	at com.menumitratCommonAPITestScript.loginTestScript.verifyloginUsingValidInputData(loginTestScript.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- verifyloginUsingValidInputData -->
</testsuite> <!-- com.menumitratCommonAPITestScript.loginTestScript -->
