<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-G790OGBU" name="com.menumitratCommonAPITestScript.ResendOTPTestScript" tests="6" failures="0" timestamp="5 May 2025 08:21:13 GMT" time="0.685" errors="2">
  <testcase name="resendOTPusingInvalidData" time="0.107" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript"/>
  <testcase name="resendOTPusingInvalidData" time="0.109" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript"/>
  <testcase name="resendOTPusingInvalidData" time="0.112" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript"/>
  <testcase name="resendOTPusingInvalidData" time="0.100" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript">
    <error type="com.menumitra.utilityclass.customException" message="Error in negative test case resendotp_002: Error validating response: success response validate failed: Acutal response does not matched expected response expected [{msg={mobile=Please provide mobile}}] but found [{detail=Please provide mobile number}]">
      <![CDATA[com.menumitra.utilityclass.customException: Error in negative test case resendotp_002: Error validating response: success response validate failed: Acutal response does not matched expected response expected [{msg={mobile=Please provide mobile}}] but found [{detail=Please provide mobile number}]
	at com.menumitratCommonAPITestScript.ResendOTPTestScript.resendOTPusingInvalidData(ResendOTPTestScript.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- resendOTPusingInvalidData -->
  <testcase name="verifyRessendOTPUSingPositiveInputData" time="0.148" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript">
    <error type="com.menumitra.utilityclass.customException" message="Error verifying resend OTP using positive input data: Error validating response: success response validate failed: Acutal response does not matched expected response expected [{role=owner}] but found [{role=owner, detail=Your OTP is sent successfully.}]">
      <![CDATA[com.menumitra.utilityclass.customException: Error verifying resend OTP using positive input data: Error validating response: success response validate failed: Acutal response does not matched expected response expected [{role=owner}] but found [{role=owner, detail=Your OTP is sent successfully.}]
	at com.menumitratCommonAPITestScript.ResendOTPTestScript.verifyRessendOTPUSingPositiveInputData(ResendOTPTestScript.java:223)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- verifyRessendOTPUSingPositiveInputData -->
  <testcase name="resendOTPusingInvalidData" time="0.109" classname="com.menumitratCommonAPITestScript.ResendOTPTestScript"/>
</testsuite> <!-- com.menumitratCommonAPITestScript.ResendOTPTestScript -->
